name: CI

on:
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  ubuntu:
    runs-on: ubuntu-latest
    name: Ubuntu
    steps:
     - name: Checkout
       uses: actions/checkout@v2
     - name: Build libwss
       run: |
          make
          sudo make install
          make tests
          ./test
  freebsd-14:
    runs-on: ubuntu-24.04
    name: FreeBSD
    steps:
      - uses: actions/checkout@v4
      - name: Build libwss
        uses: vmactions/freebsd-vm@v1
        with:
          usesh: true
          run: |
            pkg install -y gcc gmake
            gmake
            gmake install
            gmake tests
            ./test
  freebsd-14-bsd-make:
    runs-on: ubuntu-24.04
    name: FreeBSD with BSD make
    steps:
      - uses: actions/checkout@v4
      - name: Build libwss
        uses: vmactions/freebsd-vm@v1
        with:
          usesh: true
          run: |
            pkg install -y gcc
            make
            make install
            make tests
            ./test